# Generated by Django 4.0.1 on 2022-01-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_student_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
    ]
