# Generated by Django 4.0.1 on 2022-01-21 05:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0004_alter_student_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('active_object', django.db.models.manager.Manager()),
            ],
        ),
    ]
