# Generated by Django 4.0.1 on 2022-01-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0005_alter_student_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'collage',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'princi',
            },
        ),
    ]
