# Generated by Django 4.0.1 on 2022-01-25 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0006_collage_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='Collage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.collage'),
        ),
    ]
