# Generated by Django 4.0.1 on 2022-01-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0007_principal_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='second_app.collage')),
            ],
            options={
                'db_table': 'dept',
            },
        ),
    ]
