# Generated by Django 4.0.1 on 2022-01-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0010_subject'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table=' subject',
        ),
    ]
