# Generated by Django 4.0.1 on 2022-01-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0011_alter_subject_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='second_app.Student'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
