# Generated by Django 4.0.1 on 2022-01-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0012_subject_student_alter_subject_total_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpartment',
            name='Collage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='second_app.collage'),
        ),
    ]
