# Generated by Django 4.0.1 on 2022-01-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0014_alter_dpartment_collage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Dpartment',
            new_name='dpartment',
        ),
    ]
