# Generated by Django 4.0.1 on 2022-01-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0015_rename_dpartment_student_dpartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dpartment',
            new_name='Dpartment',
        ),
    ]
